import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app"></meta>
        <link rel="icon"></link>
      </Head>

      <main className="h-screen flex items-center justify-center">
        <form className="bg-white flex rounded-lg w-1/2 font-Inter">
          <div className="flex-1 text-gray-700 p-20">
            <h1 className="text-3xl pb-2 font-Inter text-center">
              Forgot password?
            </h1>
            <p className="text-gray-500">
              {" "}
              Please enter the email you use to sign in.
            </p>

            <div className="mt-6">
              <div className="pb-4">
                <label className="block font-Inter text-sm pb-2" htmlFor="name">
                  Email
                </label>

                <div>
                  <input
                    className="border-2 border-gray-500 p-2 rounded-md w-1/2"
                    type="text"
                    name="name"
                    placeholder="example@site.com"
                  ></input>
                </div>
              </div>
            </div>

            <button
              type="submit"
              className="bg-pink-500 text-sm 
              text-white py-3 mt-6 rounded-lg w-full"
            >
              Request for password reset
              <p>Back to sign in</p>
            </button>
          </div>
        </form>
      </main>
    </div>
  );
}
