import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app"></meta>
        <link rel="icon"></link>
      </Head>

      <main className="h-screen flex items-center justify-center">
        <form className="bg-white flex rounded-lg w-1/2 font-Inter">
          <div className="flex-1 text-gray-700 p-20">
            <h1 className="text-3xl pb-2 font-Inter text-center">Let's Go!</h1>
            <div className="mt-6">
              <div className="pb-4">
                <label className="block font-Inter text-sm pb-2" htmlFor="name">
                  Full Name
                </label>

                <div>
                  <input
                    className="border-2 border-gray-500 p-2 rounded-md w-1/2"
                    type="text"
                    name="name"
                    placeholder="John Doe"
                  ></input>
                </div>
                <div className="pb-4">
                  <label
                    className="block font-Inter text-sm pb-2"
                    htmlFor="email"
                  >
                    Email
                  </label>

                  <div>
                    <input
                      className="border-2 border-gray-500 p-2 rounded-md w-1/2"
                      type="text"
                      name="email"
                      placeholder="example@site.com"
                    ></input>
                  </div>
                </div>
                <div className="pb-4">
                  <label
                    className="block font-Inter text-sm pb-2"
                    htmlFor="password"
                  >
                    Choose Password
                  </label>

                  <div>
                    <input
                      className="border-2 border-gray-500 p-2 rounded-md w-1/2"
                      type="text"
                      name="password"
                      placeholder="Minimum 8 characters"
                    ></input>
                  </div>
                </div>

                <button
                  type="submit"
                  className="bg-pink-500 text-sm 
              text-white py-3 mt-6 rounded-lg w-full"
                >
                  Sign up
                </button>
                <button
                  type="submit"
                  className="bg-white-500 text-sm 
              text-black py-3 mt-6 rounded-lg w-full"
                >
                  Sign up with Google
                </button>
                <p>or login with SSO</p>
                <p className="text-sm text-gray-300">
                  By clicking the buttons above, you agree to our
                  <u>Terms of service</u> and <u>Privacy policy</u>
                </p>
              </div>
            </div>
          </div>
        </form>
      </main>
    </div>
  );
}
