import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app"></meta>
        <link rel="icon"></link>
      </Head>

      <main className="h-screen flex items-center justify-center">
        <form className="bg-white flex rounded-lg w-1/2 font-Inter">
          <div className="flex-1 text-gray-700 p-20">
            <h1 className="text-3xl pb-2 font-Inter text-center">
              Welcome Back!
            </h1>
            <div className="mt-6">
              <div className="pb-4">
                <label
                  className="block font-Inter text-sm pb-2"
                  htmlFor="email"
                >
                  Email
                </label>

                <div>
                  <input
                    className="border-2 border-gray-500 p-2 rounded-md w-1/2"
                    type="text"
                    name="email"
                    placeholder="Enter your email"
                  ></input>
                </div>
              </div>
              <div className="pb-4">
                <label
                  className="block font-Inter text-sm pb-2"
                  htmlFor="password"
                >
                  Password
                </label>

                <div>
                  <input
                    className="border-2 border-gray-500 p-2 rounded-md w-1/2"
                    type="text"
                    name="password"
                    placeholder="Enter password"
                  ></input>
                </div>
              </div>
              <p className="text-align:right">Forgot password?</p>

              <button
                type="submit"
                className="bg-pink-500 text-sm 
              text-white py-3 mt-6 rounded-lg w-full"
              >
                Log in
              </button>
              <button
                type="submit"
                className="bg-white-500 text-sm 
              text-black py-3 mt-6 rounded-lg w-full"
              >
                Login with Google
              </button>
              <p className="block">or login with SSO</p>
            </div>
          </div>
        </form>
      </main>
    </div>
  );
}
